name: Deploy backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'sturzdoku/backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add host fingerprint
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<'REMOTE'
            set -e
            cd /opt/app/sturzdoku/backend
            git pull origin main
            npm ci --silent
            pm2 restart backend
            pm2 save
          REMOTE
